language: python

cache: pip

python:
  - '3.6'

services:
  - postgresql
  - redis-server
  - docker

install:
  - pip install -r requirements.txt

script:
  - flake8
  - ./manage.py migrate
  - pytest
  - docker build -t pyslackers/website:latest -t pyslackers/website:$TRAVIS_BUILD_NUMBER .

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
